#!/usr/bin/env bash
# Transfer a file from our client to a server


if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign variables's arguments

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# checking the transformation if it was successfull
if [ $? -eq 0 ]
then
	echo "File was transfered successfully"
else
	echo "File transfer failed"
fi
