#!/usr/bin/env bash
# The commands used to install inginx in web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo inginx -t

sudo service nginx restart

sudo service nginx reload
