#!/usr/bin/env bash
# Double the number of webservers

# Install the nginx packages
sudo apt-get update
sudo apt-get install -y nginx

# Create an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/soukiitos permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#listen 80 default_server;#$string_for_replacement#" /etc/nginx/sites-enabled/default

# HTTP response header
sudo sed -i "server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
