#!/usr/bin/env bash
# Double the number of webservers

# Install the nginx packages
sudo apt-get update
sudo apt-get install -y nginx

# Create an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/soukiitos permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
