#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
  log 127.0.0.1 local0 notice
  maxconn 2000
  user haproxy
  group haproxy

defaults
  log           global
  mode          http
  option        httplog
  option        dontlognull
  retries       3
  option        redispatch
  timeout       connect 5000
  timeout       client  50000
  timeout       server  50000
  errorfile     400     /etc/haproxy/errors/400.http
  errorfile     403     /etc/haproxy/errors/403.http
  errorfile     408     /etc/haproxy/errors/408.http
  errorfile     500     /etc/haproxy/errors/500.http
  errorfile     502     /etc/haproxy/errors/502.http
  errorfile     503     /etc/haproxy/errors/503.http
  errorfile     504     /etc/haproxy/errors/504.http

frontend http-in
  timeout         client 50000
  bind            0:80
  default_backend servers

backend servers
  timeout  connect 5000
  timeout  server 50000
  balance  roundrobin
    server 368598-web-01 100.26.249.88:80 check
  server 368598-web-02 100.26.50.67:80 check
">> /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo service haproxy restart
