#!/usr/bin/env bash
# Configuration for keeping our ubuntu container's Nginx installation from listening on port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
sudo service nginx restart
rm /run/nginx.pid
