#!/usr/bin/env bash
#Manage manage_my_process
start_s()
{
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}
stop_s()
{
	pid_file="/var/run/my_process.pid"
	if [ -f "$pid_file" ]
	then
		pid=$(cat "$pid_file")
		pkill "$pid"
		rm "$pid_file"
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running"
	fi
}
case "$1" in
	start)
		start_s
		;;
	stop)
		stop_s
		;;
	restart)
		stop_s
		start_s
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit 0
