#!/usr/bin/env bash
#Display the time for 12 hours and 59 minutes
#Display hours from 0 to 12
#Display minutes from 1 to 59
h=0
m=1
while [ $h -ne 13 ]
do
	echo "Hour: $h"
	((h++))
	while [ $m -ne 60 ]
	do
		echo $m
		((m++))
	done
	((m = 1))
done
