#!/usr/bin/env bash
#Display The content of the current directory
#Display In a list format
#Where only the part of the name after the first dash is displayed
for list in *
do
	echo "$list" | cut -d '-' -f2-
done
